# Generated by Django 4.2.14 on 2024-07-10 19:53

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
